#include "python.h"
#include "../binding.h"
#include "binding_types.h"
#include "util/set.h"
#include <algorithm>
#include <cstring>
#include <string>
#include <vector>

// Python .pyi stub emitter — the Python sibling of typescript.cc, reading the
// same descriptors. Mapping differences from the TS backend:
//   - One flat module per C++ namespace ("sculptcore::mesh" ->
//     "sculptcore_mesh.pyi"); stubs resolve forward references natively, so
//     no intra-module ordering is needed.
//   - Template instantiations become distinct concrete classes with mangled
//     names (Python has no C++-style value templates); their members resolve
//     ParentTemplateParam to the concrete type.
//   - Vector<T> -> BoundVector[T], String -> str, T* -> T | None (T when
//     isNonNull), fixed arrays -> BoundArray[T]; the Bound* generics live in
//     the emitted _runtime.pyi and describe the ctypes runtime's wrappers.
//   - Enums -> enum.IntEnum; unions -> a TypeAlias union named after mapName.
//   - Overloaded methods merge into @overload groups.

namespace litestl::binding::generators {
using util::Set;
using util::string;
using util::Vector;

namespace {

const char *pyHeader = "# Auto-generated by LSTL_GeneratePython — do not edit.\n";

const char *primFile = R"(# Auto-generated by LSTL_GeneratePython — do not edit.
# Width-named integer aliases so signatures mirror the C++ declarations.

int8 = int
uint8 = int
int16 = int
uint16 = int
int32 = int
uint32 = int
int64 = int
uint64 = int
# Raw void* crossing the ABI as an integer address (Binder<void*>).
pointer = int
)";

const char *runtimeFile = R"(# Auto-generated by LSTL_GeneratePython — do not edit.
# Static view of the ctypes runtime's wrapper classes (sculptcore._classgen);
# generated stubs annotate against these names.

from typing import Generic, Iterator, Self, TypeVar

T = TypeVar("T")

class BoundObject:
    ptr: int
    owning: bool
    def dispose(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *exc: object) -> bool: ...

class BoundArray(Generic[T]):
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> T: ...
    def __setitem__(self, i: int, value: T) -> None: ...
    def __iter__(self) -> Iterator[T]: ...

class BoundVector(Generic[T]):
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> T: ...
    def __setitem__(self, i: int, value: T) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
)";

bool isPyKeyword(const string &s)
{
  static const char *kws[] = {
      "False",  "None",   "True",    "and",   "as",     "assert", "async",
      "await",  "break",  "class",   "continue", "def", "del",    "elif",
      "else",   "except", "finally", "for",   "from",   "global", "if",
      "import", "in",     "is",      "lambda", "nonlocal", "not",  "or",
      "pass",   "raise",  "return",  "try",   "while",  "with",   "yield"};
  for (const char *kw : kws) {
    if (strcmp(s.c_str(), kw) == 0) {
      return true;
    }
  }
  return false;
}

class PythonGenerator {
public:
  explicit PythonGenerator(Vector<const BindingBase *> &types) : rootTypes(types)
  {
  }

  util::Map<string, string> *generate();

private:
  Vector<const BindingBase *> &rootTypes;
  util::Map<string, const BindingBase *> typeMap;
  util::Map<string, string> *files = nullptr;
  // module name -> body text; imports collected separately per module.
  util::Map<string, string> moduleBodies;
  util::Map<string, Set<string>> moduleImports;
  // exported (module, name) pairs for the package index, in emission order.
  Vector<std::pair<string, string>> indexExports;

  void recurse(const BindingBase *type);

  string formatType(const BindingBase *type, const string &module);
  string className(const BindingBase *type);
  string mangleTemplateArg(const BindingBase *type);

  void addImport(const string &module, const string &fromModule, const string &name);

  void buildEnum(const types::Enum *e);
  void buildStruct(const types::Struct<void> *st);
  void buildUnion(const types::Union *u);

  template <typename ParamT>
  string formatParams(const Vector<ParamT> &params, const string &module);

  string &body(const string &module);

  static bool isSpecialStruct(const BindingBase *type);
  static string pyIdent(const string &s);
  static string moduleOf(const string &cppName);
  static string basenameOf(const string &cppName);
};

bool PythonGenerator::isSpecialStruct(const BindingBase *type)
{
  if (type->type != BindingType::Struct) {
    return false;
  }
  const auto *st = static_cast<const types::Struct<void> *>(type);
  const string full = st->buildFullName();
  return full.starts_with("litestl::util::Vector<") ||
         full.starts_with("litestl::util::String");
}

string PythonGenerator::pyIdent(const string &s)
{
  std::string out;
  for (size_t i = 0; i < s.size(); i++) {
    const char c = s[int(i)];
    const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                    (c >= '0' && c <= '9') || c == '_';
    out += ok ? c : '_';
  }
  // Collapse runs of '_' left by mangled punctuation.
  std::string collapsed;
  for (char c : out) {
    if (c == '_' && !collapsed.empty() && collapsed.back() == '_') {
      continue;
    }
    collapsed += c;
  }
  while (!collapsed.empty() && collapsed.back() == '_') {
    collapsed.pop_back();
  }
  if (collapsed.empty() || (collapsed[0] >= '0' && collapsed[0] <= '9')) {
    collapsed = "_" + collapsed;
  }
  string result(collapsed.c_str());
  if (isPyKeyword(result)) {
    result += "_";
  }
  return result;
}

string PythonGenerator::moduleOf(const string &cppName)
{
  const std::string s = cppName.c_str();
  const size_t i = s.rfind("::");
  if (i == std::string::npos) {
    return "globals_";
  }
  std::string ns = s.substr(0, i);
  size_t pos;
  while ((pos = ns.find("::")) != std::string::npos) {
    ns.replace(pos, 2, "_");
  }
  return pyIdent(string(ns.c_str()));
}

string PythonGenerator::basenameOf(const string &cppName)
{
  const std::string s = cppName.c_str();
  const size_t i = s.rfind("::");
  return string(i == std::string::npos ? s.c_str() : s.substr(i + 2).c_str());
}

string &PythonGenerator::body(const string &module)
{
  if (!moduleBodies.contains(module)) {
    moduleBodies.add(module, string(""));
    moduleImports.add(module, Set<string>());
  }
  return moduleBodies.lookup(module);
}

void PythonGenerator::addImport(const string &module,
                                const string &fromModule,
                                const string &name)
{
  if (fromModule == module) {
    return;
  }
  body(module); // ensure the import set exists
  moduleImports.lookup(module).add("from ." + fromModule + " import " + name);
}

string PythonGenerator::mangleTemplateArg(const BindingBase *type)
{
  using namespace types;
  if (type->type == BindingType::Literal) {
    const auto *lit = static_cast<const LiteralType *>(type);
    switch (lit->litType) {
    case LitType::Bool:
      return static_cast<const BoolLitType *>(lit)->data ? "true" : "false";
    case LitType::Number:
      return string(std::to_string(static_cast<const NumLitType *>(lit)->data).c_str());
    case LitType::String:
      return static_cast<const StrLitType *>(lit)->data;
    default:
      return "lit";
    }
  }
  return className(type);
}

string PythonGenerator::className(const BindingBase *type)
{
  string base = pyIdent(basenameOf(type->name));
  if (type->type == BindingType::Struct) {
    const auto *st = static_cast<const types::_StructBase *>(type);
    for (auto &tp : st->templateParams) {
      base += "_" + pyIdent(mangleTemplateArg(tp.type));
    }
  }
  return base;
}

string PythonGenerator::formatType(const BindingBase *type, const string &module)
{
  using namespace types;

  switch (type->type) {
  case BindingType::Boolean:
    return "bool";
  case BindingType::Number: {
    // subtype/flags layout is independent of Number<T>'s T (the BindingInfo
    // offsets table relies on the same fact).
    const auto *num = static_cast<const Number<int32_t> *>(type);
    if (num->subtype == NumberType::Float32 || num->subtype == NumberType::Float64) {
      return "float";
    }
    string name = type->name; // "int8".."uint64" per binding_number.h
    addImport(module, "_prim", name);
    return name;
  }
  case BindingType::Pointer: {
    const auto *ptr = static_cast<const Pointer *>(type);
    string inner = formatType(ptr->ptrType, module);
    return ptr->isNonNull ? inner : inner + " | None";
  }
  case BindingType::Reference:
    return formatType(static_cast<const Reference *>(type)->refType, module);
  case BindingType::Array: {
    const auto *array = static_cast<const Array<BindingBase> *>(type);
    addImport(module, "_runtime", "BoundArray");
    return "BoundArray[" + formatType(array->arrayType, module) + "]";
  }
  case BindingType::ParentTemplParam:
    return formatType(static_cast<const ParentTemplateParam *>(type)->concreteType,
                      module);
  case BindingType::Enum: {
    string name = className(type);
    addImport(module, moduleOf(type->name), name);
    return name;
  }
  case BindingType::Union: {
    const auto *u = static_cast<const Union *>(type);
    string name = pyIdent(basenameOf(u->mapName));
    addImport(module, moduleOf(u->mapName), name);
    return name;
  }
  case BindingType::Struct: {
    const auto *st = static_cast<const types::Struct<void> *>(type);
    const string full = st->buildFullName();
    if (full.starts_with("litestl::util::Vector<")) {
      addImport(module, "_runtime", "BoundVector");
      return "BoundVector[" + formatType(st->templateParams[0].type, module) + "]";
    }
    if (full.starts_with("litestl::util::String")) {
      return "str";
    }
    string name = className(type);
    addImport(module, moduleOf(type->name), name);
    return name;
  }
  default:
    return "object";
  }
}

void PythonGenerator::recurse(const BindingBase *type)
{
  if (typeMap.contains(type->buildFullName())) {
    return;
  }

  switch (type->type) {
  case BindingType::Struct: {
    const auto *st = static_cast<const types::Struct<void> *>(type);
    typeMap.add(type->buildFullName(), type);
    for (auto &member : st->members) {
      recurse(member.type);
    }
    for (auto &param : st->templateParams) {
      recurse(param.type);
    }
    for (const types::Method *m : st->methods) {
      if (m->returnType) {
        recurse(m->returnType);
      }
      for (const auto &p : m->params) {
        recurse(p.type);
      }
    }
    for (const types::Constructor *c : st->constructors) {
      for (const auto &p : c->params) {
        recurse(p.type);
      }
    }
    break;
  }
  case BindingType::Array:
    typeMap.add(type->name, type);
    recurse(static_cast<const types::Array<void> *>(type)->arrayType);
    break;
  case BindingType::Pointer:
    typeMap.add(type->name, type);
    recurse(static_cast<const types::Pointer *>(type)->ptrType);
    break;
  case BindingType::Reference:
    typeMap.add(type->name, type);
    recurse(static_cast<const types::Reference *>(type)->refType);
    break;
  case BindingType::Enum:
    typeMap.add(type->name, type);
    break;
  case BindingType::Union: {
    const auto *u = static_cast<const types::Union *>(type);
    typeMap.add(type->name, type);
    recurse(u->disPropType);
    for (auto &pair : u->structs) {
      recurse(pair.type);
    }
    break;
  }
  case BindingType::ParentTemplParam:
    recurse(static_cast<const types::ParentTemplateParam *>(type)->concreteType);
    break;
  default:
    break;
  }
}

void PythonGenerator::buildEnum(const types::Enum *e)
{
  const string module = moduleOf(e->name);
  const string name = className(e);
  string s = "\nclass " + name + "(IntEnum):\n";
  if (e->items.size() == 0) {
    s += "    ...\n";
  }
  for (auto &item : e->items) {
    s += "    " + pyIdent(item.name) + " = " +
         string(std::to_string(item.value).c_str()) + "\n";
  }
  body(module) += s;
  moduleImports.lookup(module).add("from enum import IntEnum");
  indexExports.append({module, name});
}

template <typename ParamT>
string PythonGenerator::formatParams(const Vector<ParamT> &params, const string &module)
{
  string out = "self";
  for (size_t i = 0; i < params.size(); i++) {
    const auto &p = params[int(i)];
    string pname = p.name.size() > 0 ? pyIdent(p.name) : string("arg");
    if (p.name.size() == 0) {
      pname += string(std::to_string(i).c_str());
    }
    out += ", " + pname + ": " + formatType(p.type, module);
  }
  return out;
}

void PythonGenerator::buildStruct(const types::Struct<void> *st)
{
  if (isSpecialStruct(st)) {
    return; // Vector<T>/String map to BoundVector[T]/str at every use site
  }

  const string module = moduleOf(st->name);
  const string name = className(st);
  string s = "\nclass " + name + "(BoundObject):\n";
  addImport(module, "_runtime", "BoundObject");

  bool empty = true;

  Set<string> memberNames;
  for (auto &member : st->members) {
    memberNames.add(member.name);
  }

  for (auto &member : st->members) {
    const BindingBase *mtype = member.type;
    if (mtype->type == BindingType::ParentTemplParam) {
      mtype = static_cast<const types::ParentTemplateParam *>(mtype)->concreteType;
    }
    const string mname = pyIdent(member.name);
    // Embedded structs/arrays are views: readable, not assignable — surface
    // them as read-only properties. Scalars/pointers are plain annotations.
    if (mtype->type == BindingType::Struct || mtype->type == BindingType::Array) {
      s += "    @property\n";
      s += "    def " + mname + "(self) -> " + formatType(mtype, module) + ": ...\n";
    } else {
      s += "    " + mname + ": " + formatType(mtype, module) + "\n";
    }
    empty = false;
  }

  // Overloaded methods share a name; merge them into an @overload group.
  util::Map<string, int> nameCounts;
  for (const types::Method *m : st->methods) {
    if (!nameCounts.contains(m->name)) {
      nameCounts.add(m->name, 0);
    }
    nameCounts.lookup(m->name)++;
  }

  for (const types::Method *m : st->methods) {
    if (memberNames.contains(m->name)) {
      continue; // runtime member property shadows the method
    }
    if (nameCounts.lookup(m->name) > 1) {
      s += "    @overload\n";
      moduleImports.lookup(module).add("from typing import overload");
    }
    s += "    def " + pyIdent(m->name) + "(" + formatParams(m->params, module) +
         ") -> ";
    s += m->returnType ? formatType(m->returnType, module) : string("None");
    s += ": ...\n";
    empty = false;
  }

  if (empty) {
    s += "    ...\n";
  }

  body(module) += s;
  indexExports.append({module, name});
}

void PythonGenerator::buildUnion(const types::Union *u)
{
  const string module = moduleOf(u->mapName);
  const string name = pyIdent(basenameOf(u->mapName));

  string s = "\n" + name + ": TypeAlias = ";
  int i = 0;
  for (auto &pair : u->structs) {
    if (i++ > 0) {
      s += " | ";
    }
    s += formatType(pair.type, module);
  }
  if (i == 0) {
    s += "object";
  }
  s += "\n";

  body(module) += s;
  moduleImports.lookup(module).add("from typing import TypeAlias");
  indexExports.append({module, name});
}

util::Map<string, string> *PythonGenerator::generate()
{
  files = alloc::New<util::Map<string, string>>("generatePython result");

  for (const auto type : rootTypes) {
    recurse(type);
  }

  for (auto type : typeMap.values()) {
    if (type->type == BindingType::Enum) {
      buildEnum(static_cast<const types::Enum *>(type));
    }
  }
  for (auto type : typeMap.values()) {
    if (type->type == BindingType::Struct) {
      buildStruct(static_cast<const types::Struct<void> *>(type));
    }
  }
  for (auto type : typeMap.values()) {
    if (type->type == BindingType::Union) {
      buildUnion(static_cast<const types::Union *>(type));
    }
  }

  files->add("_prim.pyi", string(primFile));
  files->add("_runtime.pyi", string(runtimeFile));

  for (auto &module : moduleBodies.keys()) {
    // Sorted imports keep the output stable and diff-friendly.
    std::vector<std::string> imports;
    for (auto &imp : moduleImports.lookup(module)) {
      imports.push_back(imp.c_str());
    }
    std::sort(imports.begin(), imports.end());

    string content = pyHeader;
    for (auto &imp : imports) {
      content += string(imp.c_str()) + "\n";
    }
    content += moduleBodies.lookup(module);
    files->add(module + ".pyi", content);
  }

  string index = pyHeader;
  index += "from ._runtime import BoundArray as BoundArray\n";
  index += "from ._runtime import BoundObject as BoundObject\n";
  index += "from ._runtime import BoundVector as BoundVector\n";
  Set<string> indexSeen;
  for (auto &[module, name] : indexExports) {
    // Same basename in two namespaces: first module keeps the short export
    // (importing both would shadow); the loser stays importable via its module.
    if (indexSeen.contains(name)) {
      continue;
    }
    indexSeen.add(name);
    index += "from ." + module + " import " + name + " as " + name + "\n";
  }
  files->add("__init__.pyi", index);

  return files;
}

} // namespace

util::Map<util::string, util::string> *generatePython(
    Vector<const BindingBase *> &types)
{
  PythonGenerator gen(types);
  return gen.generate();
}

} // namespace litestl::binding::generators
